import type { Metadata } from "next";
import { Josefin_Sans, Indie_Flower } from "next/font/google";
import "./globals.css";
import { ClientOnly } from "./component/ClientOnly";
import { Navbar } from "./component/navbar/Navbar";

const Josefin = Josefin_Sans({
  variable: "--font-body",
  subsets: ["latin"],
});

const Indie = Indie_Flower({
  variable: "--font-title",
  subsets: ["latin"],
  weight:["400"]
});

export const metadata: Metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Josefin.variable} ${Indie.variable} antialiased `}
      >
        <ClientOnly>
          <Navbar />
          {children}
        </ClientOnly>
      </body>
    </html>
  );
}
